name: 0.0.$(Rev:r)

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - projects

pr:
  autoCancel: true
  drafts: true
  branches:
    include:
      - main
  paths:
    include:
      - projects

pool:
  vmImage: ubuntu-latest

variables:
  - group: azuredevops
  - group: github
  - group: terraform-backend
  - group: terraform-version
  - name: tf_in_automation
    value: true
  - name: project_folder
    value: projects

stages:
  - stage: 'build'

    jobs:
      - job: 
        displayName: 'Infrastructure Plan'
        steps:
          - checkout: self
            fetchDepth: 1

          - template: '../pipeline-templates/prepare-credentials.yml'
          - template: '../pipeline-templates/pin-terraform.yml'
          - template: '../pipeline-templates/terraform-init.yml'

          - task: Bash@3
            displayName: 'Terraform Plan'
            env:
              ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
              ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(AZURE_TENANT_ID)
              AZDO_PERSONAL_ACCESS_TOKEN: $(AZUREDEVOPS_PAT)
              AZDO_ORG_SERVICE_URL: $(AZUREDEVOPS_URL)
              GITHUB_PAT: $(GITHUB_PAT)
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
            inputs:
              targetType: 'inline'
              workingDirectory: $(project_folder)
              script: |
                set -euo pipefail

                if [ ${BUILD_REASON} == 'PullRequest' ]; then
                  export TF_CLI_ARGS="-lock=false"
                fi

                terraform plan \
                  -input=false \
                  -var="azuredevops_pat=${AZDO_PERSONAL_ACCESS_TOKEN}" \
                  -var="azuredevops_url=${AZDO_ORG_SERVICE_URL}" \
                  -var="github_pat=${GITHUB_PAT}" \
                  -var="aws_access_key_id=${AWS_ACCESS_KEY_ID}" \
                  -var="aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" \
                  -out ${BUILD_BUILDNUMBER}.tfplan

          - template: '../pipeline-templates/publish-plan.yml'

  - stage: deploy

    jobs:
      - deployment: terraform
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        displayName: 'Change Infrastructure'
        environment: 'terraform-root'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: '../pipeline-templates/extract-plan.yml'
                - template: '../pipeline-templates/prepare-credentials.yml'
                - template: '../pipeline-templates/pin-terraform.yml'

                - task: Bash@3
                  displayName: 'Terraform Apply'
                  env:
                    ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
                    ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
                    ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
                    ARM_TENANT_ID: $(AZURE_TENANT_ID)
                    AZDO_PERSONAL_ACCESS_TOKEN: $(AZUREDEVOPS_PAT)
                    AZDO_ORG_SERVICE_URL: $(AZUREDEVOPS_URL)
                  inputs:
                    targetType: 'inline'
                    workingDirectory: $(project_folder)
                    script: |
                      set -euo pipefail
      
                      terraform apply \
                        -input=false \
                        ${BUILD_BUILDNUMBER}.tfplan