# Terraform provider does not currently support assigning service principals to Azure AD roles.
# Use this powershell script to assign Application Administrator to the principal generated by this module.
resource "local_file" "add_azureadroles_ps1" {
  for_each = toset(var.application_administrator_script_name[*])

  filename = each.key
  content = templatefile(
    "${path.module}/templates/Add-AzureAdRoles.ps1.hcl",
    {
      principal_id = azuread_service_principal.sp.id,
      roles        = var.aad_roles
    }
  )
}