# Terraform provider does not currently support assigning service principals to Azure AD roles.
# Use this powershell script to assign AppliCation Administrator to the principal generated by this module.
resource "local_file" "add_azureadroles_ps1" {
  for_each = toset(var.application_administrator_script_name[*])

  filename = each.key
  content  = data.template_file.add_azureadroles_ps1.rendered
}

data "template_file" "add_azureadroles_ps1" {
  template = file("${path.module}/templates/Add-AzureAdRoles.ps1.hcl")
  vars = {
    principal_id = azuread_service_principal.sp.id
  }
}

