locals {
  aad_role_script = templatefile(
    "${path.module}/templates/add-azuread-role.sh.hcl",
    {
      principal_id = azuread_service_principal.sp.id,
      roles        = var.aad_roles
    }
  )
}

# Terraform provider does not currently support assigning service principals to Azure AD roles.
# Use this powershell script to assign Application Administrator to the principal generated by this module.
resource "azurerm_key_vault_secret" "backend_config" {
  key_vault_id = var.key_vault.id
  name         = "add-azuread-roles-sh"
  value        = local.aad_role_script
}